# NumPy

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the <a href='https://pydata.org/'>PyData</a> ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

NumPy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Importing NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

## NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

### Why use Numpy array? Why not just a list?

There are lot's of reasons to use a Numpy array instead of a "standard" python list object. Our main reasons are:
* Memory Efficiency of Numpy Array vs list
* Easily expands to N-dimensional objects
* Speed of calculations of numpy array
* Broadcasting operations and functions with numpy
* All the data science and machine learning libraries we use are built with Numpy


In [3]:
# tab -> list of possible method
# shift+tab -> signature of method (argument)

## Creating NumPy Arrays from Objects

### From a Python List

We can create an array by directly converting a list or list of lists:

In [10]:
array = np.array([1,2,3])
print(array)
print(type(array))

[1 2 3]
<class 'numpy.ndarray'>


In [26]:
matrix = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(matrix)
print(type(matrix))
print(type(matrix[0]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [24]:
matrix = np.array(([1,2],[4,5,6],[7,8,9]))
print(matrix)
print(type(matrix))
print(type(matrix[0]))

[list([1, 2]) list([4, 5, 6]) list([7, 8, 9])]
<class 'numpy.ndarray'>
<class 'list'>


C:\Users\elmeh\AppData\Local\Temp\ipykernel_13104\3688484477.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  matrix = np.array(([1,2],[4,5,6],[7,8,9]))


In [27]:
matrix2 = np.array(([1,2],[4,5,6],[7,8,9]),dtype=object)
print(matrix2)
print(type(matrix2))
print(type(matrix2[0]))

[list([1, 2]) list([4, 5, 6]) list([7, 8, 9])]
<class 'numpy.ndarray'>
<class 'list'>


## Built-in Methods to create arrays

There are lots of built-in ways to generate arrays.

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

np.arrange(start,end,step) 

- start by default equal 0, step by default equal 1 
- end not included

In [31]:
print(np.arange(10))
print(np.arange(5,10))
print(np.arange(5,20,4))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[ 5  9 13 17]


### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [145]:
print(np.zeros(3))
print(np.ones(5))

TypeError: Cannot interpret '2' as a data type

In [147]:
np.zeros((3,3))
np.ones((4,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
- stop included

In [152]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [153]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [49]:
np.random.rand(3)

array([0.59635527, 0.77864982, 0.65305821])

In [50]:
np.random.rand(5,5)

array([[0.44804468, 0.79872813, 0.87127935, 0.31472164, 0.67885887],
       [0.32394724, 0.17745406, 0.91447302, 0.33857085, 0.74933412],
       [0.49186513, 0.84478575, 0.09726331, 0.92435688, 0.39839864],
       [0.99451788, 0.49623505, 0.79457894, 0.75997709, 0.9385255 ],
       [0.55284606, 0.02625181, 0.73939929, 0.104704  , 0.96250128]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [53]:
np.random.randn(2)

array([-0.21749018,  0.61807884])

In [54]:
np.random.randn(2,7)

array([[-0.02391668, -1.64045318, -0.89272473,  0.51638174, -0.90845857,
         1.37633436, -1.51651433],
       [-0.27136662, -0.46584133, -0.9865977 , -0.74213159,  0.95468204,
         0.70361835,  0.04816453]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [58]:
np.random.randint(1,100)

94

In [62]:
np.random.randint(1,100,5)

array([95, 54, 32, 62, 59])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [97]:
np.random.seed(44)
print(np.random.rand(10))
print(np.random.rand(2))
print(np.random.rand(1))

[0.83484215 0.1047961  0.74464048 0.36050084 0.35931084 0.60923838
 0.39377955 0.40907261 0.50990241 0.71014799]
[0.96052623 0.45662111]
[0.42765152]


In [96]:
np.random.seed(44)
print(np.random.rand(6))
print(np.random.rand(4))
print(np.random.rand(3))

[0.83484215 0.1047961  0.74464048 0.36050084 0.35931084 0.60923838]
[0.39377955 0.40907261 0.50990241 0.71014799]
[0.96052623 0.45662111 0.42765152]


## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [107]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
print("array ->",arr)
print("random array ->" ,ranarr)

array -> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
random array -> [14 34 31 38 22 13 30  5 16  4]


### Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

shape=(10,) : Cela indique qu'il s'agit d'un tableau 1D avec 10 éléments. La virgule dans le tuple est simplement une convention de NumPy pour représenter même les tableaux unidimensionnels comme des tableaux bidimensionnels avec une dimension supplémentaire (le nombre de colonnes). Dans le cas de shape=(10,), il n'y a qu'une seule dimension, mais la virgule est là pour maintenir la cohérence avec le format utilisé pour les tableaux bidimensionnels.

In [171]:
arr.shape

(25,)

In [109]:
ranarr.shape

(10,)

### Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [155]:
# from array to matrix
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [116]:
np.arange(10).reshape(5,2)
np.arange(10).reshape(5,3)
# 5*3 != 10

ValueError: cannot reshape array of size 10 into shape (5,3)

In [136]:
arr.shape

(25,)

In [139]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [140]:
arr.reshape(1,25).shape

(1, 25)

In [141]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [157]:
arr.reshape(25,1).shape

(25, 1)

In [165]:
print(arr.shape)
print(arr.reshape(25,1).shape)
print(arr.reshape(25,2).shape)

(25,)
(25, 1)


ValueError: cannot reshape array of size 25 into shape (25,2)

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [119]:
ranarr

array([14, 34, 31, 38, 22, 13, 30,  5, 16,  4])

In [130]:
print("max= ",ranarr.max())
print("Arg max= ",ranarr.argmax())
print("min= ",ranarr.min())
print("Arg min= ",ranarr.argmin())

max=  38
Arg max=  3
min=  4
Arg min=  9


### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [143]:
arr.dtype

dtype('int32')

In [144]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

### size Vs shape

La différence entre shape et size dans NumPy réside dans l'information qu'ils fournissent à propos d'un tableau.

- shape :
     La propriété shape renvoie un tuple qui décrit le nombre d'éléments le long de chaque dimension d'un tableau.
    Exemple : Si arr est un tableau de forme (3, 4), cela signifie qu'il a 3 lignes et 4 colonnes, et arr.shape renverra le tuple (3, 4).
    
- size :
    La propriété size renvoie le nombre total d'éléments dans le tableau.  
    Exemple : Si arr est un tableau de forme (3, 4), alors arr.size renverra le nombre total d'éléments, soit 12.

In [166]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.size)

5
