# NumPy Operations

In [3]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Arithmetic

You can easily perform *array with array* arithmetic, or *scalar with array* arithmetic. Let's see some examples:

### Array Array operations

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan
arr/arr

C:\Users\elmeh\AppData\Local\Temp\ipykernel_2448\205474414.py:3: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

### Array scalar operations

In [8]:
[1,2,3]*2

[1, 2, 3, 1, 2, 3]

In [9]:
#np_array operation broadcasting
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr+12

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [9]:
arr/4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [10]:
arr-10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [11]:
# Also a warning (but not an error) relating to infinity
1/arr

C:\Users\elmeh\AppData\Local\Temp\ipykernel_3896\616699925.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>Let's show some common ones:

In [13]:
# Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [16]:
# Trigonometric Functions
np.sin(arr)
np.cos(arr)
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [19]:
# Taking the Natural Logarithm
np.log(arr)
#np.log(arr[1:])

C:\Users\elmeh\AppData\Local\Temp\ipykernel_3896\2786156613.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Summary Statistics on Arrays

NumPy also offers common summary statistics like <em>sum</em>, <em>mean</em> and <em>max</em>. You would call these as methods on an array.

In [20]:
arr.sum()

45

In [21]:
arr.mean()

4.5

In [22]:
arr.max()

9

In [23]:
arr.min()

0

In [26]:
# Variance
arr.var()

8.25

In [25]:
# Standard deviation
arr.std()

2.8722813232690143

## Axis Logic
When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.

Let's see how this affects our summary statistic calculations from above.

By passing in <tt>axis=0</tt>, we're returning an array of sums along the vertical axis, essentially <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='https://www.statology.org/wp-content/uploads/2022/06/numpyaxis1-768x319.jpg' width=400/>

In [27]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr_2d.sum()

78

In [33]:
# sum by rows
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [32]:
# sum by columns
arr_2d.sum(axis=1)

array([10, 26, 42])

In [34]:
arr_2d.max(axis=0)

array([ 9, 10, 11, 12])

In [35]:
arr_2d.mean(axis=1)

array([ 2.5,  6.5, 10.5])