# NumPy Indexing and Selection

In this notebook we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [3]:
#Get a value at an index
arr[2]

2

### Slicing

In [4]:
#Slicing : Get values in a range : [start:end:step] (the end not included)
arr[0:6:4]

array([0, 4])

In [5]:
print(type(arr[0:6]),type(arr[2]))

<class 'numpy.ndarray'> <class 'numpy.int32'>


## Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [6]:
#Setting a value with index 
arr[0]=200

#Show
arr

array([200,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
#Important notes on Slices
slice_of_arr = arr[0:7]

#Show slice
slice_of_arr

array([100, 100, 100, 100, 100,   5,   6])

In [9]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99])

### Now note the changes also occur in our original array!

In [10]:
arr

array([99, 99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

### Data is not copied, it's a view of the original array! This avoids memory problems!

In [11]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [12]:
arr_2d = np.eye(10)
#Show
arr_2d

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
#Indexing row
print(arr_2d[1])
print(arr_2d[1,:])

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
# Format is arr_2d[row][col] or arr_2d[row,col]

print(arr_2d[2,2])
print(arr_2d[2][2])

1.0
1.0


### 2D array slicing

arr_2d[ slicing row , slicing column ]

In [15]:
#Shape (2,2) from top right corner

print(arr_2d[:2,8:])

[[0. 0.]
 [0. 0.]]


In [16]:
arr_2d[:2,1:]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
#Attention 

print(arr_2d[0:4,0:3][0:1])

arr_2d_prim = arr_2d[0:4,0:3]

print(arr_2d_prim[0:1])

[[1. 0. 0.]]
[[1. 0. 0.]]


## More Indexing Help
Indexing a 2D matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching *NumPy indexing* to find useful images, like this one:

<img src='https://lectures.scientific-python.org/_images/numpy_indexing.png' width=500/> Image source: https://lectures.scientific-python.org/intro/numpy/array_object.html#indexing-and-slicing

## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [18]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [20]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [21]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])